# Generated by Django 3.2.16 on 2023-01-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
