# Generated by Django 4.1.4 on 2023-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_delete_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
