# Generated by Django 4.1.4 on 2023-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
